# Load staging.env into .env.local (overrides .env) and start the dev server against AWS RDS.
# Usage: .\scripts\run-staging.ps1
#        .\scripts\run-staging.ps1 -TestOnly   # only write .env.local and test DB

param(
  [switch]$TestOnly
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$envFile = Join-Path $root "staging.env"
if (-not (Test-Path $envFile)) {
  $envFile = Join-Path $root ".env.staging"
}

if (-not (Test-Path $envFile)) {
  Write-Error "staging.env not found. Create it in the project root."
}

$vars = @{}
Get-Content $envFile | ForEach-Object {
  $line = $_.Trim()
  if ($line -eq "" -or $line.StartsWith("#")) { return }
  $eq = $line.IndexOf("=")
  if ($eq -lt 1) { return }
  $name = $line.Substring(0, $eq).Trim()
  $value = $line.Substring($eq + 1).Trim().Trim('"')
  $vars[$name] = $value
}

if ($vars["DATABASE_URL"] -match "YOUR_PASSWORD_HERE") {
  Write-Host ""
  Write-Host "Edit staging.env and replace YOUR_PASSWORD_HERE with the password from AWS Secrets Manager." -ForegroundColor Red
  exit 1
}

if ($vars["DATABASE_URL"] -match '^postgresql://([^:]+):([^@]+)@(.+)$') {
  $dbUser = $Matches[1]
  $dbPass = $Matches[2]
  $dbRest = $Matches[3]
  # Decode if already encoded, then encode once for Prisma
  try { $dbPass = [uri]::UnescapeDataString($dbPass) } catch {}
  $vars["DATABASE_URL"] = "postgresql://${dbUser}:$([uri]::EscapeDataString($dbPass))@${dbRest}"
}

$localEnv = Join-Path $root ".env.local"
$lines = @(
  "# Auto-generated by run-staging.ps1 - do not commit",
  "# Overrides .env so local dev uses AWS RDS",
  ""
)
foreach ($key in ($vars.Keys | Sort-Object)) {
  $lines += "$key=`"$($vars[$key])`""
}
Set-Content -Path $localEnv -Value ($lines -join "`n") -Encoding UTF8

Write-Host "Wrote .env.local from staging.env" -ForegroundColor Green

# Next.js does not override variables already set in the shell (stale DATABASE_URL breaks login).
Remove-Item Env:DATABASE_URL -ErrorAction SilentlyContinue
foreach ($key in $vars.Keys) {
  Set-Item -Path "env:$key" -Value $vars[$key]
}

# Keep .env.production in sync (go-live / npm start use NODE_ENV=production).
& (Join-Path $PSScriptRoot "prepare-production-env.ps1") | Out-Null

Write-Host "Synced .env.production from staging.env" -ForegroundColor Green

Set-Location $root
Write-Host "Testing database connection..." -ForegroundColor Cyan
node (Join-Path $PSScriptRoot "test-db-connection.js")
if ($LASTEXITCODE -ne 0) {
  Write-Host ""
  Write-Host "Database connection failed - login will show errors until this is fixed." -ForegroundColor Red
  Write-Host "The password in staging.env does not match AWS RDS." -ForegroundColor Yellow
  Write-Host "Fix: run .\scripts\update-rds-password.ps1 and paste the password from:" -ForegroundColor Yellow
  Write-Host "  AWS Console > Secrets Manager > rds!db-d2849d7a-..." -ForegroundColor Yellow
  exit 1
}

if ($TestOnly) {
  Write-Host "Database connection OK." -ForegroundColor Green
  exit 0
}

Write-Host "Starting Patient Vault at http://localhost:3000" -ForegroundColor Cyan
npm run dev
